#!/bin/bash
path="/home/red/Documents/ProjectsDit/ewwWidgets"

state=$(eww -c "$path" get notifOpen)

if [ "$state" == "true" ]; then
  eww -c "$path" close notifT
  eww -c "$path" update notifOpen="false"
else
  eww -c "$path" open notifT
  eww -c "$path" update notifOpen="true"
fi
