#!/bin/bash

# Function to check Bluetooth status
check_bluetooth_status() {
    bluetooth_status=$(rfkill list bluetooth | grep -i "soft blocked: yes")

    if [ -n "$bluetooth_status" ]; then
        echo "󰂲"
    else
        echo "󰂱"
    fi
}

# Function to toggle Bluetooth
toggle_bluetooth() {
    bluetooth_status=$(rfkill list bluetooth | grep -i "soft blocked: yes")

    if [ -n "$bluetooth_status" ]; then
        echo "Turning Bluetooth ON..."
        rfkill unblock 0
    else
        echo "Turning Bluetooth OFF..."
        rfkill block 0
    fi
}

# Check command line arguments
case "$1" in
    --status)
        check_bluetooth_status
        ;;
    --toggle)
        toggle_bluetooth
        ;;
    *)
        echo "Usage: $0 {--status|--toggle}"
        exit 1
        ;;
esac

